# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_dotL2 <- function(f1, f2, grid) {
    .Call(`_densityFPCA_cpp_dotL2`, f1, f2, grid)
}

cpp_calCdf <- function(pdf, grid) {
    .Call(`_densityFPCA_cpp_calCdf`, pdf, grid)
}

cpp_distWass <- function(cdf1, cdf2, grid, p) {
    .Call(`_densityFPCA_cpp_distWass`, cdf1, cdf2, grid, p)
}

